import sqlite3
from typing import Literal
from langchain_core.messages import SystemMessage, HumanMessage
from langgraph.graph import StateGraph, END, START 

# Imports from refactored modules
from states import AgentState, VectorDBQueries, SemanticCheckResult
from prompts import (
    TEXT2SQL_DECOMPOSITION_SYSTEM_PROMPT,
    get_text2sql_generation_prompt,
    get_text2sql_debugger_system_prompt,
    get_text2sql_semantic_system_prompt,
    get_text2sql_semantic_user_prompt,
    TEXT2SQL_FORMAT_SYSTEM_PROMPT,
    get_text2sql_format_user_prompt
)
from models import (
    llm, qwen, DB_PATH, coll_schema, coll_examples, coll_evidence, coll_values
)

class Text2SQL:
    def __init__(self):
        self.agent = self.create_agent()
    
    def generate_vect_db_query(self, state: AgentState):
        """
        Node 1: Decompose the user's question into 4 specific search queries.
        """
        print(f"  [INFO] Generating Vector DB Queries... ")
        
        structured_llm = qwen.with_structured_output(VectorDBQueries)
        
        queries_object = structured_llm.invoke([
            SystemMessage(content=TEXT2SQL_DECOMPOSITION_SYSTEM_PROMPT),
            HumanMessage(content=state['question'])
        ])
        
        print("   schema:   ", queries_object.schema_query)
        print("   evidence: ", queries_object.knowledge_query)
        print("   value:    ", queries_object.value_query)
        print("   example:  ", queries_object.example_query)

        return {
            "vect_queries": {
                "schema": queries_object.schema_query,
                "evidence": queries_object.knowledge_query,
                "value": queries_object.value_query,
                "example": queries_object.example_query
            }
        }

    def retrieve_schema(self, state: AgentState):
        """
        Node 2: Execute retrieval against the Vector Databases.
        Uses the list of strings generated by the Metadata Extractor.
        """
        queries = state['vect_queries']
        print(f"  [INFO] Retrieving Schema & Metadata...")

        res_schema = []
        for q_text in queries['schema']:
            results = coll_schema.query(query_texts=[q_text], n_results=1)
            
            if results['documents'] and results['documents'][0]:
                doc_content = "\n".join(results['documents'][0])
                res_schema.append(doc_content)
        
        final_schema = "\n---\n".join(list(set(res_schema)))
        return {"db_results": [final_schema]}

    def retrieve_examples(self, state: AgentState):
        """
        Node: Execute retrieval for Few-Shot SQL examples.
        """
        queries = state['vect_queries']
        print(f"  [INFO] Retrieving Examples...")

        search_terms = queries.get("example", state['question'])
        if isinstance(search_terms, list):
            search_term = search_terms[0]
        else:
            search_term = search_terms

        res_examples = coll_examples.query(query_texts=[search_term], n_results=2)
        
        examples_list = []
        if res_examples['metadatas'] and res_examples['metadatas'][0]:
            for meta, doc_text in zip(res_examples['metadatas'][0], res_examples['documents'][0]):
                sql_code = meta.get('query', 'No SQL found')
                examples_list.append(f"Question: {doc_text}\nSQL: {sql_code}")

        examples_txt = "\n---\n".join(examples_list)
        if not examples_txt:
            examples_txt = "No relevant SQL examples found."

        return {"db_results": [examples_txt]}

    def retrieve_evidence(self, state: AgentState):
        """
        Node 2: Execute retrieval for Business Logic and Evidence.
        """
        queries = state['vect_queries']
        print(f"  [INFO] Retrieving Evidence...")
        
        search_terms = queries['evidence']
        unique_docs = set()
        
        for term in search_terms:
            res_evidence = coll_evidence.query(query_texts=[term], n_results=4)
            if res_evidence['documents'] and res_evidence['documents'][0]:
                for doc in res_evidence['documents'][0]:
                    unique_docs.add(doc)

        evidence_txt = "\n\n".join(list(unique_docs))
        return {"db_results": [evidence_txt]}

    def retrieve_values(self, state: AgentState):
        """
        Node: Execute retrieval for specific Data Vocabulary / Categorical Values.
        """
        queries = state['vect_queries']
        print(f"  [INFO] Retrieving Values...")
        
        search_terms = queries["value"]
        unique_value_mappings = set()
        
        for term in search_terms:
            res_values = coll_values.query(query_texts=[term], n_results=7)

            if res_values.get('metadatas') and res_values['metadatas'][0]:
                for meta in res_values['metadatas'][0]:
                    val = meta.get('value', 'Unknown')
                    col = meta.get('column_name', 'Unknown')
                    tbl = meta.get('table_name', 'Unknown')
                    unique_value_mappings.add(f"Found Value: '{val}' in Table: {tbl}, Column: {col}")

        values_txt = "\n".join(list(unique_value_mappings))
        if not values_txt:
            values_txt = "No specific categorical value matches found."

        return {"db_results": [values_txt]}

    def generate_sql(self, state: AgentState):
        """
        Generate the SQL query using the retrieved context.
        """
        print("  [INFO] Generating SQL   ")
        full_context = "\n\n".join(state['db_results'])
        
        prompt = get_text2sql_generation_prompt(full_context, state['question'])
        response = llm.invoke([prompt])
        cleaned_sql = response.content.replace("```sql", "").replace("```", "").strip()

        print("Generated SQL: ", cleaned_sql)
        return {"sql_candidate": cleaned_sql}

    def syntax_checker(self, state: AgentState):
        """
        Node: Attempt to execute the SQL. If it fails, ask the LLM to fix it.
        """
        current_sql = state["sql_candidate"]
        retries = state.get("retry_count", 0)
        
        print(f"  [INFO] Checking Syntax (Attempt {retries + 1})")

        try:
            conn = sqlite3.connect(DB_PATH)
            cursor = conn.cursor()
            cursor.execute(current_sql)
            result_data = cursor.fetchall()
            conn.close()

            print("   [Success] SQL executed successfully.")
            return {
                "query_result": str(result_data),
                "is_sql_modified": False,
                "retry_count": 0
            }

        except Exception as e:
            error_msg = str(e)
            print(f"   [Error] SQL failed: {error_msg}")
                
            if retries >= 3:
                print("   [Fail] Max retries reached.")
                return {
                    "is_sql_modified": False,
                    "query_result": f"Error: Failed after 3 attempts. Last error: {error_msg}",
                    "retry_count": 0
                }
        
            full_context = "\n\n".join(state['db_results'])
            system_prompt = get_text2sql_debugger_system_prompt(full_context)
        
            messages = [
                SystemMessage(content=system_prompt),
                HumanMessage(content=f"Original Query: {current_sql}\nSQLite Error: {error_msg}")
            ]
        
            response = llm.invoke(messages)
            fixed_sql = response.content.replace("```sql", "").replace("```", "").strip()
            print("Fixed SQL: ", fixed_sql)

            return {
                "sql_candidate": fixed_sql,
                "is_sql_modified": True,
                "retry_count": retries + 1
            }

    def should_continue_syntax(self, state: AgentState) -> Literal["syntax_checker", "semantic_checker"]:
        if state.get("is_sql_modified", False):
            return "syntax_checker"
        else:
            return "semantic_checker"        

    def semantic_checker(self, state: AgentState):
        """
        Audit the SQL logic against the user's original intent.
        """
        print("  [INFO] Semantic Logic Review ")
        current_sql = state["sql_candidate"]
        original_question = state["question"]
        
        structured_llm = qwen.with_structured_output(SemanticCheckResult)
        full_context = "\n\n".join(state['db_results'])
    
        system_prompt = get_text2sql_semantic_system_prompt(full_context)
        user_prompt = get_text2sql_semantic_user_prompt(original_question, current_sql)
    
        result = structured_llm.invoke([
            SystemMessage(content=system_prompt),
            HumanMessage(content=user_prompt)
        ])
    
        print(f"   [Reasoning]: {result.reasoning}")

        if result.is_semantically_correct:
            print("   [Success] Logic is sound.")
            return {"is_sql_modified": False}
        else:       
            print("   [Warning] Logic error detected. Updating SQL.")
            print(f"  [INFO] Corrected SQL: {result.corrected_sql}")
            return {
                "sql_candidate": result.corrected_sql,
                "is_sql_modified": True,
                "retry_count": 0
            }

    def check_semantic_modification(self, state: AgentState) -> Literal["syntax_checker", "format_result"]:
        if state.get("is_sql_modified", False):
            print("   >> Looping back to Syntax Checker")
            return "syntax_checker"
        else:
            print("   >> Proceeding to Finish")
            return "format_result"

    def format_result(self, state: AgentState):
        """
        Convert raw database results into a natural language response.
        """
        print("  [Node] Formatting Final Response")

        if "Error:" in state.get("query_result", ""):
            answer = f"I'm sorry, I encountered an issue: {state['query_result']}"
        else:
            user_question, raw_data = state["question"], state["query_result"]
            
            user_message = get_text2sql_format_user_prompt(user_question, raw_data)
            response = llm.invoke([
                SystemMessage(content=TEXT2SQL_FORMAT_SYSTEM_PROMPT),
                HumanMessage(content=user_message)
            ])

            answer = response.content
            print("Final Answer: ", answer)

        return {
            "final_output": answer,
            "data_results": [{"question": state["question"], "answer": answer}]
        }      

    def create_agent(self):
        workflow = StateGraph(AgentState)

        workflow.add_node("generate_vect_db_query", self.generate_vect_db_query)
        workflow.add_node("schema_db", self.retrieve_schema)
        workflow.add_node("example_db", self.retrieve_examples)
        workflow.add_node("evidence_db", self.retrieve_evidence)
        workflow.add_node("cell_value_db", self.retrieve_values)
        workflow.add_node("generate_query", self.generate_sql)
        workflow.add_node("syntax_checker", self.syntax_checker)
        workflow.add_node("semantic_checker", self.semantic_checker)
        workflow.add_node("format_result", self.format_result)

        workflow.add_edge(START, "generate_vect_db_query")

        workflow.add_edge("generate_vect_db_query", "schema_db")
        workflow.add_edge("generate_vect_db_query", "example_db")
        workflow.add_edge("generate_vect_db_query", "evidence_db")
        workflow.add_edge("generate_vect_db_query", "cell_value_db")

        workflow.add_edge("schema_db", "generate_query")
        workflow.add_edge("example_db", "generate_query")
        workflow.add_edge("evidence_db", "generate_query")
        workflow.add_edge("cell_value_db", "generate_query")
        workflow.add_edge("generate_query", "syntax_checker")

        workflow.add_conditional_edges(
            "syntax_checker",
            self.should_continue_syntax,
            {
                "syntax_checker": "syntax_checker",
                "semantic_checker": "semantic_checker"
            }
        )

        workflow.add_conditional_edges(
            "semantic_checker",
            self.check_semantic_modification,
            {
                "syntax_checker": "syntax_checker",
                "format_result": "format_result"
            }
        )

        workflow.add_edge("format_result", END)
        return workflow.compile()

    def run_agent(self, question: str, config: dict):
        result = self.agent.invoke({"question": question}, config=config)
        return result